
CREATE TABLE MEDICAMENT_TRAITEMENT(
MEDICAMENT_ID bigint,
TRAITEMENT_ID bigint,
  PRIMARY KEY (MEDICAMENT_ID,TRAITEMENT_ID),
     FOREIGN KEY (MEDICAMENT_ID)
     REFERENCES MEDICAMENT (id),
     FOREIGN KEY (TRAITEMENT_ID)
     REFERENCES TRAITEMENT (id)
);
INSERT INTO MEDICAMENT_TRAITEMENT (MEDICAMENT_ID, TRAITEMENT_ID)  VALUES (1,1);
INSERT INTO MEDICAMENT_TRAITEMENT (MEDICAMENT_ID, TRAITEMENT_ID)  VALUES (1,2);