DROP TABLE IF EXISTS MEDICAMENT_TRAITEMENT;
DROP TABLE IF EXISTS TRAITEMENT;
DROP TABLE IF EXISTS MEDICAMENT;
DROP TABLE IF EXISTS CONSULTATION;
DROP TABLE IF EXISTS PATIENT;

CREATE TABLE PATIENT (
    id SERIAL NOT NULL,
    first_name VARCHAR(128) NOT NULL,
    middle_name VARCHAR(100) NULL,
    last_name VARCHAR(128) NOT NULL,
    birth_date DATE NOT NULL,
    sexe integer,
    identity_card_number VARCHAR(100)  NULL,
    blood_group INTEGER NULL,

    CONSTRAINT patient_pk PRIMARY KEY (id)
);

CREATE TABLE CONSULTATION (
	id SERIAL NOT NULL,
	date DATE NOT NULL,
	histoire_maladie VARCHAR(2056),
	patient_id bigint NOT NULL,
	CONSTRAINT consultation_pk PRIMARY KEY (id),
	foreign key (patient_id) references PATIENT(id)
);

CREATE TABLE MEDICAMENT (
	id SERIAL NOT NULL,
	dci VARCHAR(100) NOT NULL,
	nom_commercial VARCHAR(200) NOT NULL,
	description VARCHAR(200) NOT NULL,
	indications VARCHAR(200) NULL,
	contre_indication VARCHAR(200) NULL,
	CONSTRAINT medicament_pk PRIMARY KEY (id)
);

CREATE TABLE TRAITEMENT(
	id SERIAL NOT NULL,
	date_trt DATE NOT NULL,
	type_trt Integer NOT NULL,
	CONSULTATION_ID bigint null,
	CONSTRAINT traitement_pk PRIMARY KEY (id),
	foreign key (CONSULTATION_ID) references CONSULTATION(id)
);

CREATE TABLE MEDICAMENT_TRAITEMENT(
	MEDICAMENT_ID bigint,
	TRAITEMENT_ID bigint,
	CONSTRAINT medicament_traitement_pk PRIMARY KEY (MEDICAMENT_ID,TRAITEMENT_ID),
	FOREIGN KEY (MEDICAMENT_ID)
	REFERENCES MEDICAMENT (id),
	FOREIGN KEY (TRAITEMENT_ID)
	REFERENCES TRAITEMENT (id)
);